name: sentiment-stocks
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pyspark
  - kafka-python
  - transformers
  - elasticsearch=8.13.2
  - faker
  - ipykernel
  - pandas
  - pyyaml
  - yfinance
  - requests
  - pymongo
  - torch
  - torchvision
  - torchaudio